# Generated by Django 3.2.6 on 2021-08-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortened_url',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
