# Generated by Django 3.2.5 on 2021-07-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20210730_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('low', 'LOW'), ('medium', 'MEDIUM')], default='low', max_length=10),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
