# Generated by Django 3.2.5 on 2021-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('user_win', models.IntegerField(default=0)),
                ('computer_win', models.IntegerField(default=0)),
                ('implement', models.CharField(choices=[('rock', 'ROCK'), ('scissors', 'SCISSORS'), ('paper', 'PAPER')], default='rock', max_length=10)),
            ],
        ),
    ]
