# Generated by Django 3.2.5 on 2021-08-12 18:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posttime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 12, 18, 41, 7, 929724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joindate',
            field=models.DateField(default=datetime.datetime(2021, 8, 12, 18, 41, 7, 929724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 12, 18, 41, 7, 932716, tzinfo=utc)),
        ),
    ]
