# Generated by Django 3.2.5 on 2021-08-13 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='chirp_app.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postdate',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 18, 35, 30, 698124, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_banner',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tag',
            field=models.CharField(default='1111', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='postdate',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 18, 35, 30, 701116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posttime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 13, 18, 35, 30, 698124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joindate',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 18, 35, 30, 699121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 13, 18, 35, 30, 701116, tzinfo=utc)),
        ),
    ]
