# Generated by Django 3.2.5 on 2021-08-12 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0002_auto_20210812_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postdate',
            field=models.DateField(default=datetime.datetime(2021, 8, 12, 18, 42, 12, 1775, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='postdate',
            field=models.DateField(default=datetime.datetime(2021, 8, 12, 18, 42, 12, 4777, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posttime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 12, 18, 42, 12, 1775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joindate',
            field=models.DateField(default=datetime.datetime(2021, 8, 12, 18, 42, 12, 2771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 12, 18, 42, 12, 4777, tzinfo=utc)),
        ),
    ]
