# Generated by Django 3.2.5 on 2021-08-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogpost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='user',
        ),
    ]
