# Generated by Django 3.2.5 on 2021-08-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Cohort', models.CharField(max_length=100)),
                ('fav_topic', models.CharField(max_length=100)),
                ('fav_teacher', models.CharField(max_length=100)),
                ('Capstone', models.URLField(max_length=250)),
            ],
        ),
    ]
