# Generated by Django 3.2.5 on 2021-07-29 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 21, 21, 53, 515956, tzinfo=utc)),
        ),
    ]
