# Generated by Django 3.2.5 on 2021-08-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
