# Generated by Django 3.2.5 on 2021-08-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_playlist_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
