# Generated by Django 3.2.5 on 2021-07-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500)),
                ('startdate', models.DateTimeField()),
                ('duedate', models.DateTimeField()),
            ],
        ),
    ]
