# Generated by Django 3.2.5 on 2021-07-29 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todomodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
