# Generated by Django 3.2.5 on 2021-07-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_todomodel_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('H', 'HIGH'), ('L', 'LOW'), ('M', 'MEDIUM')], default='HIGH', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.priority'),
        ),
    ]
