# Generated by Django 3.2.5 on 2021-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_alter_priority_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='choice',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='HIGH', max_length=7),
        ),
    ]
