# Generated by Django 3.2.5 on 2021-07-30 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_alter_priority_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duetime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='starttime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='priority',
            name='choice',
            field=models.CharField(blank=True, choices=[('medium', 'MEDIUM'), ('high', 'HIGH'), ('low', 'LOW')], default='HIGH', max_length=7),
        ),
    ]
