# Generated by Django 3.2.5 on 2021-07-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todomodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.todomodel'),
        ),
    ]
