# Generated by Django 3.2.5 on 2021-07-30 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_auto_20210730_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='choice',
            field=models.CharField(blank=True, choices=[('medium', 'MEDIUM'), ('low', 'LOW'), ('high', 'HIGH')], default='HIGH', max_length=7),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
