# Generated by Django 3.2.5 on 2021-08-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0016_alter_priority_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='choice',
            field=models.CharField(blank=True, choices=[('low', 'LOW'), ('high', 'HIGH'), ('medium', 'MEDIUM')], default='HIGH', max_length=7),
        ),
    ]
