# Generated by Django 3.2.5 on 2021-08-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0017_alter_priority_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='choice',
            field=models.CharField(blank=True, choices=[('medium', 'MEDIUM'), ('high', 'HIGH'), ('low', 'LOW')], default='HIGH', max_length=7),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.priority'),
        ),
    ]
