# Generated by Django 3.2.5 on 2021-07-29 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
