# Generated by Django 3.2.5 on 2021-07-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
